### ISSUE TITLE
Add `webp` Image Support

### ISSUE THREAD

**Issue by getBoolean** [AlexandreSenpai/Enma#83]
I noticed NH has recently started using webp images, see 538021

This causes the following error:

```
Traceback (most recent call last):
  File "G:\GitHub\comic_download\utils\nh_download.py", line 669, in download_***
    manga: Manga | None = nh_source.get(nh_id)
                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\enma\infra\core\utils\cache.py", line 34, in wrapper
    new_execution = function(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\enma\infra\adapters\repositories\nhentai.py", line 188, in get
    chapter = self.__create_chapter(url=url,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\enma\infra\adapters\repositories\nhentai.py", line 158, in __create_chapter
    mime = MIME[page.get('t').upper()]
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\enum.py", line 814, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'W'
```

**Comment by AlexandreSenpai** [comment]
Thank you very much for fixing this issue!!
This fix is going to be available on Enma 2.4.3 version

**Comment by AlexandreSenpai** [comment]
Can you share which id did you use?

**Comment by AlexandreSenpai** [comment]
You're right, sorry HAHAHAHA
I'm kinda sleepy.

**Comment by AlexandreSenpai** [comment]
New version is now available, feel free to run
```sh
pip install enma==2.4.3
```
